# Generated by Django 2.2.12 on 2020-05-03 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this object was created.",
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this object was last updated.",
                        verbose_name="Last update date",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label of the listing.",
                        max_length=125,
                        verbose_name="Label",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=None,
                        editable=False,
                        help_text="When the listing was published.",
                        null=True,
                        verbose_name="Published at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={"verbose_name": "Listing", "verbose_name_plural": "Listings",},
        ),
    ]
